# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main_part', '0002_auto_20170514_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
